# position: 1
PREFIX schema: <https://schema.org/>
PREFIX haOrg: <https://data.hetarchief.be/ns/organization/>

SELECT DISTINCT 
?organization_id
?schema_contact_type
?schema_email
?schema_telephone
#?created_at
#?updated_at
FROM <https://data.hetarchief.be/graph/thesaurus/thesauri>
FROM <https://data.hetarchief.be/graph/thesaurus/licenses>
FROM <https://data.hetarchief.be/graph/organization>
FROM <https://data.hetarchief.be/graph/thesaurus/namenlijst>
FROM <https://data.hetarchief.be/graph/metadata/OR-0z70w1b>
FROM <https://data.hetarchief.be/graph/metadata/OR-zc7rt4f>
FROM <https://data.hetarchief.be/graph/metadata/OR-v97zq9j>
FROM <https://data.hetarchief.be/graph/metadata/OR-gh9b857>
WHERE {
  ?organization_id a haOrg:ContentPartner;
      schema:contactPoint ?point.
  
  ?point schema:contactType ?schema_contact_type.
  
  OPTIONAL {
     ?point schema:email ?schema_email ;
  }

  OPTIONAL {
     ?point schema:telephone ?schema_telephone .
  } 
}